version: '3'

services:
  postgres:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env.docker

  dal:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - $DAL_PORT:$DAL_PORT
    command: sh -c "
        scripts/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT -t 0 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:$DAL_PORT
      "

    # Map directories with code for hot reloading
    volumes:
      - ./dal:/dal/dal
      - ./dms:/dal/dms
      - ./lms:/dal/lms
