version: '3'

services:
  postgres:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env.docker

  dms:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - $DMS_PORT:$DMS_PORT
    command: sh -c "
        scripts/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT -t 0 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:$DMS_PORT
      "

    # Map directories with code for hot reloading
    volumes:
      - ./backend:/dms/backend
      - ./dms:/dms/dms
      - ./mil_lms_backend:/dms/mil_lms_backend
