name: "Back end"

on: [push]

jobs:
  main:
    name: "Build, tests, style, lint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run:  cp tgbot/.env.example tgbot/.env
      - name: "Build back end Docker container"
        run:  docker-compose build back-end
      - name: "Run tests"
        run:  docker-compose run back-end scripts/test.sh
      - name: "Check code style"
        run:  docker-compose run back-end scripts/format.sh
      - name: "Lint code"
        run:  docker-compose run back-end scripts/lint.sh
