name: Back end

on: [push]

jobs:
  code-style:
    name: Code style checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install python3
          pip3 install pipenv && pipenv install --system --deploy --dev
      - name: Check code style
        run: cd back-end && scripts/run-yapf.sh

  lint:
    name: Linter checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install python3
          pip3 install pipenv && pipenv install --system --deploy --dev
      - name: Lint code
        run: cd back-end && scripts/run-pylint.sh

  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install python3
          pip3 install pipenv && pipenv install --system --deploy --dev
      - name: Run pytest tests
        run: cd back-end && pytest
