name: "Front end"

on: [push]

jobs:
  main:
    name: "Build, style"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run:  cp tgbot/.env.example tgbot/.env
      - name: "Install NPM packages"
        run: cd front-end && npm install
      - name: "Check code style"
        run: cd front-end && npx prettier --check .
      - name: "Build front end container"
        run:  docker-compose build front-end
